<?php
/**
 * DlpAdvancedDocumentDetectionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DlpAdvancedDocumentDetectionRequest Class Doc Comment
 *
 * @category Class
 * @description Request object for advanced DLP document detection with 29 PII detection types including health-related data.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DlpAdvancedDocumentDetectionRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DlpAdvancedDocumentDetectionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'input_file' => 'string',
        'file_name' => 'string',
        'recognition_mode' => 'string',
        'allow_email_address' => 'bool',
        'allow_phone_number' => 'bool',
        'allow_street_address' => 'bool',
        'allow_person_name' => 'bool',
        'allow_birth_date' => 'bool',
        'allow_passport_number' => 'bool',
        'allow_drivers_license' => 'bool',
        'allow_social_security_number' => 'bool',
        'allow_taxpayer_id' => 'bool',
        'allow_credit_card_number' => 'bool',
        'allow_credit_card_expiration_date' => 'bool',
        'allow_credit_card_verification_code' => 'bool',
        'allow_bank_account_number' => 'bool',
        'allow_iban' => 'bool',
        'allow_health_insurance_number' => 'bool',
        'allow_bearer_token' => 'bool',
        'allow_http_cookie' => 'bool',
        'allow_private_keys' => 'bool',
        'allow_credentials' => 'bool',
        'allow_deep_web_urls' => 'bool',
        'allow_source_code' => 'bool',
        'allow_ip_address' => 'bool',
        'allow_mac_address' => 'bool',
        'allow_health_insurance_member_id' => 'bool',
        'allow_health_injury_or_disease' => 'bool',
        'allow_health_type_of_treatment' => 'bool',
        'allow_health_date_and_time_of_treatment' => 'bool',
        'allow_health_plan_beneficiary_number' => 'bool',
        'allow_health_payments_made_for_treatment' => 'bool',
        'allow_faces' => 'bool',
        'allow_vehicle_id' => 'bool',
        'allow_device_id' => 'bool',
        'allow_names_of_relatives' => 'bool',
        'allow_health_universal_record_locator' => 'bool',
        'allow_biometrics' => 'bool',
        'provide_analysis_rationale' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'input_file' => 'byte',
        'file_name' => null,
        'recognition_mode' => null,
        'allow_email_address' => null,
        'allow_phone_number' => null,
        'allow_street_address' => null,
        'allow_person_name' => null,
        'allow_birth_date' => null,
        'allow_passport_number' => null,
        'allow_drivers_license' => null,
        'allow_social_security_number' => null,
        'allow_taxpayer_id' => null,
        'allow_credit_card_number' => null,
        'allow_credit_card_expiration_date' => null,
        'allow_credit_card_verification_code' => null,
        'allow_bank_account_number' => null,
        'allow_iban' => null,
        'allow_health_insurance_number' => null,
        'allow_bearer_token' => null,
        'allow_http_cookie' => null,
        'allow_private_keys' => null,
        'allow_credentials' => null,
        'allow_deep_web_urls' => null,
        'allow_source_code' => null,
        'allow_ip_address' => null,
        'allow_mac_address' => null,
        'allow_health_insurance_member_id' => null,
        'allow_health_injury_or_disease' => null,
        'allow_health_type_of_treatment' => null,
        'allow_health_date_and_time_of_treatment' => null,
        'allow_health_plan_beneficiary_number' => null,
        'allow_health_payments_made_for_treatment' => null,
        'allow_faces' => null,
        'allow_vehicle_id' => null,
        'allow_device_id' => null,
        'allow_names_of_relatives' => null,
        'allow_health_universal_record_locator' => null,
        'allow_biometrics' => null,
        'provide_analysis_rationale' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'input_file' => 'InputFile',
        'file_name' => 'FileName',
        'recognition_mode' => 'RecognitionMode',
        'allow_email_address' => 'AllowEmailAddress',
        'allow_phone_number' => 'AllowPhoneNumber',
        'allow_street_address' => 'AllowStreetAddress',
        'allow_person_name' => 'AllowPersonName',
        'allow_birth_date' => 'AllowBirthDate',
        'allow_passport_number' => 'AllowPassportNumber',
        'allow_drivers_license' => 'AllowDriversLicense',
        'allow_social_security_number' => 'AllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'AllowTaxpayerID',
        'allow_credit_card_number' => 'AllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'AllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'AllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'AllowBankAccountNumber',
        'allow_iban' => 'AllowIBAN',
        'allow_health_insurance_number' => 'AllowHealthInsuranceNumber',
        'allow_bearer_token' => 'AllowBearerToken',
        'allow_http_cookie' => 'AllowHttpCookie',
        'allow_private_keys' => 'AllowPrivateKeys',
        'allow_credentials' => 'AllowCredentials',
        'allow_deep_web_urls' => 'AllowDeepWebUrls',
        'allow_source_code' => 'AllowSourceCode',
        'allow_ip_address' => 'AllowIpAddress',
        'allow_mac_address' => 'AllowMacAddress',
        'allow_health_insurance_member_id' => 'AllowHealthInsuranceMemberID',
        'allow_health_injury_or_disease' => 'AllowHealthInjuryOrDisease',
        'allow_health_type_of_treatment' => 'AllowHealthTypeOfTreatment',
        'allow_health_date_and_time_of_treatment' => 'AllowHealthDateAndTimeOfTreatment',
        'allow_health_plan_beneficiary_number' => 'AllowHealthPlanBeneficiaryNumber',
        'allow_health_payments_made_for_treatment' => 'AllowHealthPaymentsMadeForTreatment',
        'allow_faces' => 'AllowFaces',
        'allow_vehicle_id' => 'AllowVehicleID',
        'allow_device_id' => 'AllowDeviceID',
        'allow_names_of_relatives' => 'AllowNamesOfRelatives',
        'allow_health_universal_record_locator' => 'AllowHealthUniversalRecordLocator',
        'allow_biometrics' => 'AllowBiometrics',
        'provide_analysis_rationale' => 'ProvideAnalysisRationale'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'input_file' => 'setInputFile',
        'file_name' => 'setFileName',
        'recognition_mode' => 'setRecognitionMode',
        'allow_email_address' => 'setAllowEmailAddress',
        'allow_phone_number' => 'setAllowPhoneNumber',
        'allow_street_address' => 'setAllowStreetAddress',
        'allow_person_name' => 'setAllowPersonName',
        'allow_birth_date' => 'setAllowBirthDate',
        'allow_passport_number' => 'setAllowPassportNumber',
        'allow_drivers_license' => 'setAllowDriversLicense',
        'allow_social_security_number' => 'setAllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'setAllowTaxpayerId',
        'allow_credit_card_number' => 'setAllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'setAllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'setAllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'setAllowBankAccountNumber',
        'allow_iban' => 'setAllowIban',
        'allow_health_insurance_number' => 'setAllowHealthInsuranceNumber',
        'allow_bearer_token' => 'setAllowBearerToken',
        'allow_http_cookie' => 'setAllowHttpCookie',
        'allow_private_keys' => 'setAllowPrivateKeys',
        'allow_credentials' => 'setAllowCredentials',
        'allow_deep_web_urls' => 'setAllowDeepWebUrls',
        'allow_source_code' => 'setAllowSourceCode',
        'allow_ip_address' => 'setAllowIpAddress',
        'allow_mac_address' => 'setAllowMacAddress',
        'allow_health_insurance_member_id' => 'setAllowHealthInsuranceMemberId',
        'allow_health_injury_or_disease' => 'setAllowHealthInjuryOrDisease',
        'allow_health_type_of_treatment' => 'setAllowHealthTypeOfTreatment',
        'allow_health_date_and_time_of_treatment' => 'setAllowHealthDateAndTimeOfTreatment',
        'allow_health_plan_beneficiary_number' => 'setAllowHealthPlanBeneficiaryNumber',
        'allow_health_payments_made_for_treatment' => 'setAllowHealthPaymentsMadeForTreatment',
        'allow_faces' => 'setAllowFaces',
        'allow_vehicle_id' => 'setAllowVehicleId',
        'allow_device_id' => 'setAllowDeviceId',
        'allow_names_of_relatives' => 'setAllowNamesOfRelatives',
        'allow_health_universal_record_locator' => 'setAllowHealthUniversalRecordLocator',
        'allow_biometrics' => 'setAllowBiometrics',
        'provide_analysis_rationale' => 'setProvideAnalysisRationale'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'input_file' => 'getInputFile',
        'file_name' => 'getFileName',
        'recognition_mode' => 'getRecognitionMode',
        'allow_email_address' => 'getAllowEmailAddress',
        'allow_phone_number' => 'getAllowPhoneNumber',
        'allow_street_address' => 'getAllowStreetAddress',
        'allow_person_name' => 'getAllowPersonName',
        'allow_birth_date' => 'getAllowBirthDate',
        'allow_passport_number' => 'getAllowPassportNumber',
        'allow_drivers_license' => 'getAllowDriversLicense',
        'allow_social_security_number' => 'getAllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'getAllowTaxpayerId',
        'allow_credit_card_number' => 'getAllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'getAllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'getAllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'getAllowBankAccountNumber',
        'allow_iban' => 'getAllowIban',
        'allow_health_insurance_number' => 'getAllowHealthInsuranceNumber',
        'allow_bearer_token' => 'getAllowBearerToken',
        'allow_http_cookie' => 'getAllowHttpCookie',
        'allow_private_keys' => 'getAllowPrivateKeys',
        'allow_credentials' => 'getAllowCredentials',
        'allow_deep_web_urls' => 'getAllowDeepWebUrls',
        'allow_source_code' => 'getAllowSourceCode',
        'allow_ip_address' => 'getAllowIpAddress',
        'allow_mac_address' => 'getAllowMacAddress',
        'allow_health_insurance_member_id' => 'getAllowHealthInsuranceMemberId',
        'allow_health_injury_or_disease' => 'getAllowHealthInjuryOrDisease',
        'allow_health_type_of_treatment' => 'getAllowHealthTypeOfTreatment',
        'allow_health_date_and_time_of_treatment' => 'getAllowHealthDateAndTimeOfTreatment',
        'allow_health_plan_beneficiary_number' => 'getAllowHealthPlanBeneficiaryNumber',
        'allow_health_payments_made_for_treatment' => 'getAllowHealthPaymentsMadeForTreatment',
        'allow_faces' => 'getAllowFaces',
        'allow_vehicle_id' => 'getAllowVehicleId',
        'allow_device_id' => 'getAllowDeviceId',
        'allow_names_of_relatives' => 'getAllowNamesOfRelatives',
        'allow_health_universal_record_locator' => 'getAllowHealthUniversalRecordLocator',
        'allow_biometrics' => 'getAllowBiometrics',
        'provide_analysis_rationale' => 'getProvideAnalysisRationale'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['input_file'] = isset($data['input_file']) ? $data['input_file'] : null;
        $this->container['file_name'] = isset($data['file_name']) ? $data['file_name'] : null;
        $this->container['recognition_mode'] = isset($data['recognition_mode']) ? $data['recognition_mode'] : null;
        $this->container['allow_email_address'] = isset($data['allow_email_address']) ? $data['allow_email_address'] : null;
        $this->container['allow_phone_number'] = isset($data['allow_phone_number']) ? $data['allow_phone_number'] : null;
        $this->container['allow_street_address'] = isset($data['allow_street_address']) ? $data['allow_street_address'] : null;
        $this->container['allow_person_name'] = isset($data['allow_person_name']) ? $data['allow_person_name'] : null;
        $this->container['allow_birth_date'] = isset($data['allow_birth_date']) ? $data['allow_birth_date'] : null;
        $this->container['allow_passport_number'] = isset($data['allow_passport_number']) ? $data['allow_passport_number'] : null;
        $this->container['allow_drivers_license'] = isset($data['allow_drivers_license']) ? $data['allow_drivers_license'] : null;
        $this->container['allow_social_security_number'] = isset($data['allow_social_security_number']) ? $data['allow_social_security_number'] : null;
        $this->container['allow_taxpayer_id'] = isset($data['allow_taxpayer_id']) ? $data['allow_taxpayer_id'] : null;
        $this->container['allow_credit_card_number'] = isset($data['allow_credit_card_number']) ? $data['allow_credit_card_number'] : null;
        $this->container['allow_credit_card_expiration_date'] = isset($data['allow_credit_card_expiration_date']) ? $data['allow_credit_card_expiration_date'] : null;
        $this->container['allow_credit_card_verification_code'] = isset($data['allow_credit_card_verification_code']) ? $data['allow_credit_card_verification_code'] : null;
        $this->container['allow_bank_account_number'] = isset($data['allow_bank_account_number']) ? $data['allow_bank_account_number'] : null;
        $this->container['allow_iban'] = isset($data['allow_iban']) ? $data['allow_iban'] : null;
        $this->container['allow_health_insurance_number'] = isset($data['allow_health_insurance_number']) ? $data['allow_health_insurance_number'] : null;
        $this->container['allow_bearer_token'] = isset($data['allow_bearer_token']) ? $data['allow_bearer_token'] : null;
        $this->container['allow_http_cookie'] = isset($data['allow_http_cookie']) ? $data['allow_http_cookie'] : null;
        $this->container['allow_private_keys'] = isset($data['allow_private_keys']) ? $data['allow_private_keys'] : null;
        $this->container['allow_credentials'] = isset($data['allow_credentials']) ? $data['allow_credentials'] : null;
        $this->container['allow_deep_web_urls'] = isset($data['allow_deep_web_urls']) ? $data['allow_deep_web_urls'] : null;
        $this->container['allow_source_code'] = isset($data['allow_source_code']) ? $data['allow_source_code'] : null;
        $this->container['allow_ip_address'] = isset($data['allow_ip_address']) ? $data['allow_ip_address'] : null;
        $this->container['allow_mac_address'] = isset($data['allow_mac_address']) ? $data['allow_mac_address'] : null;
        $this->container['allow_health_insurance_member_id'] = isset($data['allow_health_insurance_member_id']) ? $data['allow_health_insurance_member_id'] : null;
        $this->container['allow_health_injury_or_disease'] = isset($data['allow_health_injury_or_disease']) ? $data['allow_health_injury_or_disease'] : null;
        $this->container['allow_health_type_of_treatment'] = isset($data['allow_health_type_of_treatment']) ? $data['allow_health_type_of_treatment'] : null;
        $this->container['allow_health_date_and_time_of_treatment'] = isset($data['allow_health_date_and_time_of_treatment']) ? $data['allow_health_date_and_time_of_treatment'] : null;
        $this->container['allow_health_plan_beneficiary_number'] = isset($data['allow_health_plan_beneficiary_number']) ? $data['allow_health_plan_beneficiary_number'] : null;
        $this->container['allow_health_payments_made_for_treatment'] = isset($data['allow_health_payments_made_for_treatment']) ? $data['allow_health_payments_made_for_treatment'] : null;
        $this->container['allow_faces'] = isset($data['allow_faces']) ? $data['allow_faces'] : null;
        $this->container['allow_vehicle_id'] = isset($data['allow_vehicle_id']) ? $data['allow_vehicle_id'] : null;
        $this->container['allow_device_id'] = isset($data['allow_device_id']) ? $data['allow_device_id'] : null;
        $this->container['allow_names_of_relatives'] = isset($data['allow_names_of_relatives']) ? $data['allow_names_of_relatives'] : null;
        $this->container['allow_health_universal_record_locator'] = isset($data['allow_health_universal_record_locator']) ? $data['allow_health_universal_record_locator'] : null;
        $this->container['allow_biometrics'] = isset($data['allow_biometrics']) ? $data['allow_biometrics'] : null;
        $this->container['provide_analysis_rationale'] = isset($data['provide_analysis_rationale']) ? $data['provide_analysis_rationale'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if (!is_null($this->container['input_file']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['input_file'])) {
            $invalidProperties[] = "invalid value for 'input_file', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets input_file
     *
     * @return string
     */
    public function getInputFile()
    {
        return $this->container['input_file'];
    }

    /**
     * Sets input_file
     *
     * @param string $input_file Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and sensitive data.
     *
     * @return $this
     */
    public function setInputFile($input_file)
    {

        if (!is_null($input_file) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $input_file))) {
            throw new \InvalidArgumentException("invalid value for $input_file when calling DlpAdvancedDocumentDetectionRequest., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['input_file'] = $input_file;

        return $this;
    }

    /**
     * Gets file_name
     *
     * @return string
     */
    public function getFileName()
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     *
     * @param string $file_name Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.
     *
     * @return $this
     */
    public function setFileName($file_name)
    {
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets recognition_mode
     *
     * @return string
     */
    public function getRecognitionMode()
    {
        return $this->container['recognition_mode'];
    }

    /**
     * Sets recognition_mode
     *
     * @param string $recognition_mode Optional. Recognition mode for image processing. Options: null (default), \"Fast\", \"FastPlus\", \"FastMini\".
     *
     * @return $this
     */
    public function setRecognitionMode($recognition_mode)
    {
        $this->container['recognition_mode'] = $recognition_mode;

        return $this;
    }

    /**
     * Gets allow_email_address
     *
     * @return bool
     */
    public function getAllowEmailAddress()
    {
        return $this->container['allow_email_address'];
    }

    /**
     * Sets allow_email_address
     *
     * @param bool $allow_email_address Set to true to allow email addresses in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowEmailAddress($allow_email_address)
    {
        $this->container['allow_email_address'] = $allow_email_address;

        return $this;
    }

    /**
     * Gets allow_phone_number
     *
     * @return bool
     */
    public function getAllowPhoneNumber()
    {
        return $this->container['allow_phone_number'];
    }

    /**
     * Sets allow_phone_number
     *
     * @param bool $allow_phone_number Set to true to allow phone numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPhoneNumber($allow_phone_number)
    {
        $this->container['allow_phone_number'] = $allow_phone_number;

        return $this;
    }

    /**
     * Gets allow_street_address
     *
     * @return bool
     */
    public function getAllowStreetAddress()
    {
        return $this->container['allow_street_address'];
    }

    /**
     * Sets allow_street_address
     *
     * @param bool $allow_street_address Set to true to allow street addresses in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowStreetAddress($allow_street_address)
    {
        $this->container['allow_street_address'] = $allow_street_address;

        return $this;
    }

    /**
     * Gets allow_person_name
     *
     * @return bool
     */
    public function getAllowPersonName()
    {
        return $this->container['allow_person_name'];
    }

    /**
     * Sets allow_person_name
     *
     * @param bool $allow_person_name Set to true to allow person names in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPersonName($allow_person_name)
    {
        $this->container['allow_person_name'] = $allow_person_name;

        return $this;
    }

    /**
     * Gets allow_birth_date
     *
     * @return bool
     */
    public function getAllowBirthDate()
    {
        return $this->container['allow_birth_date'];
    }

    /**
     * Sets allow_birth_date
     *
     * @param bool $allow_birth_date Set to true to allow birth dates in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBirthDate($allow_birth_date)
    {
        $this->container['allow_birth_date'] = $allow_birth_date;

        return $this;
    }

    /**
     * Gets allow_passport_number
     *
     * @return bool
     */
    public function getAllowPassportNumber()
    {
        return $this->container['allow_passport_number'];
    }

    /**
     * Sets allow_passport_number
     *
     * @param bool $allow_passport_number Set to true to allow passport numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPassportNumber($allow_passport_number)
    {
        $this->container['allow_passport_number'] = $allow_passport_number;

        return $this;
    }

    /**
     * Gets allow_drivers_license
     *
     * @return bool
     */
    public function getAllowDriversLicense()
    {
        return $this->container['allow_drivers_license'];
    }

    /**
     * Sets allow_drivers_license
     *
     * @param bool $allow_drivers_license Set to true to allow drivers license numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowDriversLicense($allow_drivers_license)
    {
        $this->container['allow_drivers_license'] = $allow_drivers_license;

        return $this;
    }

    /**
     * Gets allow_social_security_number
     *
     * @return bool
     */
    public function getAllowSocialSecurityNumber()
    {
        return $this->container['allow_social_security_number'];
    }

    /**
     * Sets allow_social_security_number
     *
     * @param bool $allow_social_security_number Set to true to allow social security numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowSocialSecurityNumber($allow_social_security_number)
    {
        $this->container['allow_social_security_number'] = $allow_social_security_number;

        return $this;
    }

    /**
     * Gets allow_taxpayer_id
     *
     * @return bool
     */
    public function getAllowTaxpayerId()
    {
        return $this->container['allow_taxpayer_id'];
    }

    /**
     * Sets allow_taxpayer_id
     *
     * @param bool $allow_taxpayer_id Set to true to allow taxpayer IDs in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowTaxpayerId($allow_taxpayer_id)
    {
        $this->container['allow_taxpayer_id'] = $allow_taxpayer_id;

        return $this;
    }

    /**
     * Gets allow_credit_card_number
     *
     * @return bool
     */
    public function getAllowCreditCardNumber()
    {
        return $this->container['allow_credit_card_number'];
    }

    /**
     * Sets allow_credit_card_number
     *
     * @param bool $allow_credit_card_number Set to true to allow credit card numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardNumber($allow_credit_card_number)
    {
        $this->container['allow_credit_card_number'] = $allow_credit_card_number;

        return $this;
    }

    /**
     * Gets allow_credit_card_expiration_date
     *
     * @return bool
     */
    public function getAllowCreditCardExpirationDate()
    {
        return $this->container['allow_credit_card_expiration_date'];
    }

    /**
     * Sets allow_credit_card_expiration_date
     *
     * @param bool $allow_credit_card_expiration_date Set to true to allow credit card expiration dates in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardExpirationDate($allow_credit_card_expiration_date)
    {
        $this->container['allow_credit_card_expiration_date'] = $allow_credit_card_expiration_date;

        return $this;
    }

    /**
     * Gets allow_credit_card_verification_code
     *
     * @return bool
     */
    public function getAllowCreditCardVerificationCode()
    {
        return $this->container['allow_credit_card_verification_code'];
    }

    /**
     * Sets allow_credit_card_verification_code
     *
     * @param bool $allow_credit_card_verification_code Set to true to allow credit card verification codes in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardVerificationCode($allow_credit_card_verification_code)
    {
        $this->container['allow_credit_card_verification_code'] = $allow_credit_card_verification_code;

        return $this;
    }

    /**
     * Gets allow_bank_account_number
     *
     * @return bool
     */
    public function getAllowBankAccountNumber()
    {
        return $this->container['allow_bank_account_number'];
    }

    /**
     * Sets allow_bank_account_number
     *
     * @param bool $allow_bank_account_number Set to true to allow bank account numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBankAccountNumber($allow_bank_account_number)
    {
        $this->container['allow_bank_account_number'] = $allow_bank_account_number;

        return $this;
    }

    /**
     * Gets allow_iban
     *
     * @return bool
     */
    public function getAllowIban()
    {
        return $this->container['allow_iban'];
    }

    /**
     * Sets allow_iban
     *
     * @param bool $allow_iban Set to true to allow IBANs in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowIban($allow_iban)
    {
        $this->container['allow_iban'] = $allow_iban;

        return $this;
    }

    /**
     * Gets allow_health_insurance_number
     *
     * @return bool
     */
    public function getAllowHealthInsuranceNumber()
    {
        return $this->container['allow_health_insurance_number'];
    }

    /**
     * Sets allow_health_insurance_number
     *
     * @param bool $allow_health_insurance_number Set to true to allow health insurance numbers in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowHealthInsuranceNumber($allow_health_insurance_number)
    {
        $this->container['allow_health_insurance_number'] = $allow_health_insurance_number;

        return $this;
    }

    /**
     * Gets allow_bearer_token
     *
     * @return bool
     */
    public function getAllowBearerToken()
    {
        return $this->container['allow_bearer_token'];
    }

    /**
     * Sets allow_bearer_token
     *
     * @param bool $allow_bearer_token Set to true to allow bearer tokens in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBearerToken($allow_bearer_token)
    {
        $this->container['allow_bearer_token'] = $allow_bearer_token;

        return $this;
    }

    /**
     * Gets allow_http_cookie
     *
     * @return bool
     */
    public function getAllowHttpCookie()
    {
        return $this->container['allow_http_cookie'];
    }

    /**
     * Sets allow_http_cookie
     *
     * @param bool $allow_http_cookie Set to true to allow HTTP cookies in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowHttpCookie($allow_http_cookie)
    {
        $this->container['allow_http_cookie'] = $allow_http_cookie;

        return $this;
    }

    /**
     * Gets allow_private_keys
     *
     * @return bool
     */
    public function getAllowPrivateKeys()
    {
        return $this->container['allow_private_keys'];
    }

    /**
     * Sets allow_private_keys
     *
     * @param bool $allow_private_keys Set to true to allow private keys in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPrivateKeys($allow_private_keys)
    {
        $this->container['allow_private_keys'] = $allow_private_keys;

        return $this;
    }

    /**
     * Gets allow_credentials
     *
     * @return bool
     */
    public function getAllowCredentials()
    {
        return $this->container['allow_credentials'];
    }

    /**
     * Sets allow_credentials
     *
     * @param bool $allow_credentials Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCredentials($allow_credentials)
    {
        $this->container['allow_credentials'] = $allow_credentials;

        return $this;
    }

    /**
     * Gets allow_deep_web_urls
     *
     * @return bool
     */
    public function getAllowDeepWebUrls()
    {
        return $this->container['allow_deep_web_urls'];
    }

    /**
     * Sets allow_deep_web_urls
     *
     * @param bool $allow_deep_web_urls Set to true to allow deep web URLs (.onion) in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowDeepWebUrls($allow_deep_web_urls)
    {
        $this->container['allow_deep_web_urls'] = $allow_deep_web_urls;

        return $this;
    }

    /**
     * Gets allow_source_code
     *
     * @return bool
     */
    public function getAllowSourceCode()
    {
        return $this->container['allow_source_code'];
    }

    /**
     * Sets allow_source_code
     *
     * @param bool $allow_source_code Set to true to allow source code in the document and not flag it as sensitive data.
     *
     * @return $this
     */
    public function setAllowSourceCode($allow_source_code)
    {
        $this->container['allow_source_code'] = $allow_source_code;

        return $this;
    }

    /**
     * Gets allow_ip_address
     *
     * @return bool
     */
    public function getAllowIpAddress()
    {
        return $this->container['allow_ip_address'];
    }

    /**
     * Sets allow_ip_address
     *
     * @param bool $allow_ip_address Set to true to allow IP addresses in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowIpAddress($allow_ip_address)
    {
        $this->container['allow_ip_address'] = $allow_ip_address;

        return $this;
    }

    /**
     * Gets allow_mac_address
     *
     * @return bool
     */
    public function getAllowMacAddress()
    {
        return $this->container['allow_mac_address'];
    }

    /**
     * Sets allow_mac_address
     *
     * @param bool $allow_mac_address Set to true to allow MAC addresses in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowMacAddress($allow_mac_address)
    {
        $this->container['allow_mac_address'] = $allow_mac_address;

        return $this;
    }

    /**
     * Gets allow_health_insurance_member_id
     *
     * @return bool
     */
    public function getAllowHealthInsuranceMemberId()
    {
        return $this->container['allow_health_insurance_member_id'];
    }

    /**
     * Sets allow_health_insurance_member_id
     *
     * @param bool $allow_health_insurance_member_id Set to true to allow health insurance member IDs in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthInsuranceMemberId($allow_health_insurance_member_id)
    {
        $this->container['allow_health_insurance_member_id'] = $allow_health_insurance_member_id;

        return $this;
    }

    /**
     * Gets allow_health_injury_or_disease
     *
     * @return bool
     */
    public function getAllowHealthInjuryOrDisease()
    {
        return $this->container['allow_health_injury_or_disease'];
    }

    /**
     * Sets allow_health_injury_or_disease
     *
     * @param bool $allow_health_injury_or_disease Set to true to allow references to injuries or diseases in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthInjuryOrDisease($allow_health_injury_or_disease)
    {
        $this->container['allow_health_injury_or_disease'] = $allow_health_injury_or_disease;

        return $this;
    }

    /**
     * Gets allow_health_type_of_treatment
     *
     * @return bool
     */
    public function getAllowHealthTypeOfTreatment()
    {
        return $this->container['allow_health_type_of_treatment'];
    }

    /**
     * Sets allow_health_type_of_treatment
     *
     * @param bool $allow_health_type_of_treatment Set to true to allow references to types of medical treatment in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthTypeOfTreatment($allow_health_type_of_treatment)
    {
        $this->container['allow_health_type_of_treatment'] = $allow_health_type_of_treatment;

        return $this;
    }

    /**
     * Gets allow_health_date_and_time_of_treatment
     *
     * @return bool
     */
    public function getAllowHealthDateAndTimeOfTreatment()
    {
        return $this->container['allow_health_date_and_time_of_treatment'];
    }

    /**
     * Sets allow_health_date_and_time_of_treatment
     *
     * @param bool $allow_health_date_and_time_of_treatment Set to true to allow dates and times of medical treatment in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthDateAndTimeOfTreatment($allow_health_date_and_time_of_treatment)
    {
        $this->container['allow_health_date_and_time_of_treatment'] = $allow_health_date_and_time_of_treatment;

        return $this;
    }

    /**
     * Gets allow_health_plan_beneficiary_number
     *
     * @return bool
     */
    public function getAllowHealthPlanBeneficiaryNumber()
    {
        return $this->container['allow_health_plan_beneficiary_number'];
    }

    /**
     * Sets allow_health_plan_beneficiary_number
     *
     * @param bool $allow_health_plan_beneficiary_number Set to true to allow health plan beneficiary numbers in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthPlanBeneficiaryNumber($allow_health_plan_beneficiary_number)
    {
        $this->container['allow_health_plan_beneficiary_number'] = $allow_health_plan_beneficiary_number;

        return $this;
    }

    /**
     * Gets allow_health_payments_made_for_treatment
     *
     * @return bool
     */
    public function getAllowHealthPaymentsMadeForTreatment()
    {
        return $this->container['allow_health_payments_made_for_treatment'];
    }

    /**
     * Sets allow_health_payments_made_for_treatment
     *
     * @param bool $allow_health_payments_made_for_treatment Set to true to allow payments made for medical treatment in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthPaymentsMadeForTreatment($allow_health_payments_made_for_treatment)
    {
        $this->container['allow_health_payments_made_for_treatment'] = $allow_health_payments_made_for_treatment;

        return $this;
    }

    /**
     * Gets allow_faces
     *
     * @return bool
     */
    public function getAllowFaces()
    {
        return $this->container['allow_faces'];
    }

    /**
     * Sets allow_faces
     *
     * @param bool $allow_faces Set to true to allow identifiable human faces in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowFaces($allow_faces)
    {
        $this->container['allow_faces'] = $allow_faces;

        return $this;
    }

    /**
     * Gets allow_vehicle_id
     *
     * @return bool
     */
    public function getAllowVehicleId()
    {
        return $this->container['allow_vehicle_id'];
    }

    /**
     * Sets allow_vehicle_id
     *
     * @param bool $allow_vehicle_id Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowVehicleId($allow_vehicle_id)
    {
        $this->container['allow_vehicle_id'] = $allow_vehicle_id;

        return $this;
    }

    /**
     * Gets allow_device_id
     *
     * @return bool
     */
    public function getAllowDeviceId()
    {
        return $this->container['allow_device_id'];
    }

    /**
     * Sets allow_device_id
     *
     * @param bool $allow_device_id Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowDeviceId($allow_device_id)
    {
        $this->container['allow_device_id'] = $allow_device_id;

        return $this;
    }

    /**
     * Gets allow_names_of_relatives
     *
     * @return bool
     */
    public function getAllowNamesOfRelatives()
    {
        return $this->container['allow_names_of_relatives'];
    }

    /**
     * Sets allow_names_of_relatives
     *
     * @param bool $allow_names_of_relatives Set to true to allow names of relatives in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowNamesOfRelatives($allow_names_of_relatives)
    {
        $this->container['allow_names_of_relatives'] = $allow_names_of_relatives;

        return $this;
    }

    /**
     * Gets allow_health_universal_record_locator
     *
     * @return bool
     */
    public function getAllowHealthUniversalRecordLocator()
    {
        return $this->container['allow_health_universal_record_locator'];
    }

    /**
     * Sets allow_health_universal_record_locator
     *
     * @param bool $allow_health_universal_record_locator Set to true to allow health universal record locators (URLs) in the document and not flag them as PHI.
     *
     * @return $this
     */
    public function setAllowHealthUniversalRecordLocator($allow_health_universal_record_locator)
    {
        $this->container['allow_health_universal_record_locator'] = $allow_health_universal_record_locator;

        return $this;
    }

    /**
     * Gets allow_biometrics
     *
     * @return bool
     */
    public function getAllowBiometrics()
    {
        return $this->container['allow_biometrics'];
    }

    /**
     * Sets allow_biometrics
     *
     * @param bool $allow_biometrics Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the document and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBiometrics($allow_biometrics)
    {
        $this->container['allow_biometrics'] = $allow_biometrics;

        return $this;
    }

    /**
     * Gets provide_analysis_rationale
     *
     * @return bool
     */
    public function getProvideAnalysisRationale()
    {
        return $this->container['provide_analysis_rationale'];
    }

    /**
     * Sets provide_analysis_rationale
     *
     * @param bool $provide_analysis_rationale Set to true to include a natural language rationale explaining why each detection conclusion was formed.
     *
     * @return $this
     */
    public function setProvideAnalysisRationale($provide_analysis_rationale)
    {
        $this->container['provide_analysis_rationale'] = $provide_analysis_rationale;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


