<?php
/**
 * DlpDetectionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DlpDetectionRequest Class Doc Comment
 *
 * @category Class
 * @description Request object for DLP text detection with 23 PII detection types.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DlpDetectionRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DlpDetectionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'input_text' => 'string',
        'allow_email_address' => 'bool',
        'allow_phone_number' => 'bool',
        'allow_street_address' => 'bool',
        'allow_person_name' => 'bool',
        'allow_birth_date' => 'bool',
        'allow_passport_number' => 'bool',
        'allow_drivers_license' => 'bool',
        'allow_social_security_number' => 'bool',
        'allow_taxpayer_id' => 'bool',
        'allow_credit_card_number' => 'bool',
        'allow_credit_card_expiration_date' => 'bool',
        'allow_credit_card_verification_code' => 'bool',
        'allow_bank_account_number' => 'bool',
        'allow_iban' => 'bool',
        'allow_health_insurance_number' => 'bool',
        'allow_bearer_token' => 'bool',
        'allow_http_cookie' => 'bool',
        'allow_private_keys' => 'bool',
        'allow_credentials' => 'bool',
        'allow_deep_web_urls' => 'bool',
        'allow_source_code' => 'bool',
        'allow_ip_address' => 'bool',
        'allow_mac_address' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'input_text' => null,
        'allow_email_address' => null,
        'allow_phone_number' => null,
        'allow_street_address' => null,
        'allow_person_name' => null,
        'allow_birth_date' => null,
        'allow_passport_number' => null,
        'allow_drivers_license' => null,
        'allow_social_security_number' => null,
        'allow_taxpayer_id' => null,
        'allow_credit_card_number' => null,
        'allow_credit_card_expiration_date' => null,
        'allow_credit_card_verification_code' => null,
        'allow_bank_account_number' => null,
        'allow_iban' => null,
        'allow_health_insurance_number' => null,
        'allow_bearer_token' => null,
        'allow_http_cookie' => null,
        'allow_private_keys' => null,
        'allow_credentials' => null,
        'allow_deep_web_urls' => null,
        'allow_source_code' => null,
        'allow_ip_address' => null,
        'allow_mac_address' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'input_text' => 'InputText',
        'allow_email_address' => 'AllowEmailAddress',
        'allow_phone_number' => 'AllowPhoneNumber',
        'allow_street_address' => 'AllowStreetAddress',
        'allow_person_name' => 'AllowPersonName',
        'allow_birth_date' => 'AllowBirthDate',
        'allow_passport_number' => 'AllowPassportNumber',
        'allow_drivers_license' => 'AllowDriversLicense',
        'allow_social_security_number' => 'AllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'AllowTaxpayerID',
        'allow_credit_card_number' => 'AllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'AllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'AllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'AllowBankAccountNumber',
        'allow_iban' => 'AllowIBAN',
        'allow_health_insurance_number' => 'AllowHealthInsuranceNumber',
        'allow_bearer_token' => 'AllowBearerToken',
        'allow_http_cookie' => 'AllowHttpCookie',
        'allow_private_keys' => 'AllowPrivateKeys',
        'allow_credentials' => 'AllowCredentials',
        'allow_deep_web_urls' => 'AllowDeepWebUrls',
        'allow_source_code' => 'AllowSourceCode',
        'allow_ip_address' => 'AllowIpAddress',
        'allow_mac_address' => 'AllowMacAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'input_text' => 'setInputText',
        'allow_email_address' => 'setAllowEmailAddress',
        'allow_phone_number' => 'setAllowPhoneNumber',
        'allow_street_address' => 'setAllowStreetAddress',
        'allow_person_name' => 'setAllowPersonName',
        'allow_birth_date' => 'setAllowBirthDate',
        'allow_passport_number' => 'setAllowPassportNumber',
        'allow_drivers_license' => 'setAllowDriversLicense',
        'allow_social_security_number' => 'setAllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'setAllowTaxpayerId',
        'allow_credit_card_number' => 'setAllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'setAllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'setAllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'setAllowBankAccountNumber',
        'allow_iban' => 'setAllowIban',
        'allow_health_insurance_number' => 'setAllowHealthInsuranceNumber',
        'allow_bearer_token' => 'setAllowBearerToken',
        'allow_http_cookie' => 'setAllowHttpCookie',
        'allow_private_keys' => 'setAllowPrivateKeys',
        'allow_credentials' => 'setAllowCredentials',
        'allow_deep_web_urls' => 'setAllowDeepWebUrls',
        'allow_source_code' => 'setAllowSourceCode',
        'allow_ip_address' => 'setAllowIpAddress',
        'allow_mac_address' => 'setAllowMacAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'input_text' => 'getInputText',
        'allow_email_address' => 'getAllowEmailAddress',
        'allow_phone_number' => 'getAllowPhoneNumber',
        'allow_street_address' => 'getAllowStreetAddress',
        'allow_person_name' => 'getAllowPersonName',
        'allow_birth_date' => 'getAllowBirthDate',
        'allow_passport_number' => 'getAllowPassportNumber',
        'allow_drivers_license' => 'getAllowDriversLicense',
        'allow_social_security_number' => 'getAllowSocialSecurityNumber',
        'allow_taxpayer_id' => 'getAllowTaxpayerId',
        'allow_credit_card_number' => 'getAllowCreditCardNumber',
        'allow_credit_card_expiration_date' => 'getAllowCreditCardExpirationDate',
        'allow_credit_card_verification_code' => 'getAllowCreditCardVerificationCode',
        'allow_bank_account_number' => 'getAllowBankAccountNumber',
        'allow_iban' => 'getAllowIban',
        'allow_health_insurance_number' => 'getAllowHealthInsuranceNumber',
        'allow_bearer_token' => 'getAllowBearerToken',
        'allow_http_cookie' => 'getAllowHttpCookie',
        'allow_private_keys' => 'getAllowPrivateKeys',
        'allow_credentials' => 'getAllowCredentials',
        'allow_deep_web_urls' => 'getAllowDeepWebUrls',
        'allow_source_code' => 'getAllowSourceCode',
        'allow_ip_address' => 'getAllowIpAddress',
        'allow_mac_address' => 'getAllowMacAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['input_text'] = isset($data['input_text']) ? $data['input_text'] : null;
        $this->container['allow_email_address'] = isset($data['allow_email_address']) ? $data['allow_email_address'] : null;
        $this->container['allow_phone_number'] = isset($data['allow_phone_number']) ? $data['allow_phone_number'] : null;
        $this->container['allow_street_address'] = isset($data['allow_street_address']) ? $data['allow_street_address'] : null;
        $this->container['allow_person_name'] = isset($data['allow_person_name']) ? $data['allow_person_name'] : null;
        $this->container['allow_birth_date'] = isset($data['allow_birth_date']) ? $data['allow_birth_date'] : null;
        $this->container['allow_passport_number'] = isset($data['allow_passport_number']) ? $data['allow_passport_number'] : null;
        $this->container['allow_drivers_license'] = isset($data['allow_drivers_license']) ? $data['allow_drivers_license'] : null;
        $this->container['allow_social_security_number'] = isset($data['allow_social_security_number']) ? $data['allow_social_security_number'] : null;
        $this->container['allow_taxpayer_id'] = isset($data['allow_taxpayer_id']) ? $data['allow_taxpayer_id'] : null;
        $this->container['allow_credit_card_number'] = isset($data['allow_credit_card_number']) ? $data['allow_credit_card_number'] : null;
        $this->container['allow_credit_card_expiration_date'] = isset($data['allow_credit_card_expiration_date']) ? $data['allow_credit_card_expiration_date'] : null;
        $this->container['allow_credit_card_verification_code'] = isset($data['allow_credit_card_verification_code']) ? $data['allow_credit_card_verification_code'] : null;
        $this->container['allow_bank_account_number'] = isset($data['allow_bank_account_number']) ? $data['allow_bank_account_number'] : null;
        $this->container['allow_iban'] = isset($data['allow_iban']) ? $data['allow_iban'] : null;
        $this->container['allow_health_insurance_number'] = isset($data['allow_health_insurance_number']) ? $data['allow_health_insurance_number'] : null;
        $this->container['allow_bearer_token'] = isset($data['allow_bearer_token']) ? $data['allow_bearer_token'] : null;
        $this->container['allow_http_cookie'] = isset($data['allow_http_cookie']) ? $data['allow_http_cookie'] : null;
        $this->container['allow_private_keys'] = isset($data['allow_private_keys']) ? $data['allow_private_keys'] : null;
        $this->container['allow_credentials'] = isset($data['allow_credentials']) ? $data['allow_credentials'] : null;
        $this->container['allow_deep_web_urls'] = isset($data['allow_deep_web_urls']) ? $data['allow_deep_web_urls'] : null;
        $this->container['allow_source_code'] = isset($data['allow_source_code']) ? $data['allow_source_code'] : null;
        $this->container['allow_ip_address'] = isset($data['allow_ip_address']) ? $data['allow_ip_address'] : null;
        $this->container['allow_mac_address'] = isset($data['allow_mac_address']) ? $data['allow_mac_address'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets input_text
     *
     * @return string
     */
    public function getInputText()
    {
        return $this->container['input_text'];
    }

    /**
     * Sets input_text
     *
     * @param string $input_text Text to scan for PII and sensitive data.
     *
     * @return $this
     */
    public function setInputText($input_text)
    {
        $this->container['input_text'] = $input_text;

        return $this;
    }

    /**
     * Gets allow_email_address
     *
     * @return bool
     */
    public function getAllowEmailAddress()
    {
        return $this->container['allow_email_address'];
    }

    /**
     * Sets allow_email_address
     *
     * @param bool $allow_email_address Set to true to allow email addresses in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowEmailAddress($allow_email_address)
    {
        $this->container['allow_email_address'] = $allow_email_address;

        return $this;
    }

    /**
     * Gets allow_phone_number
     *
     * @return bool
     */
    public function getAllowPhoneNumber()
    {
        return $this->container['allow_phone_number'];
    }

    /**
     * Sets allow_phone_number
     *
     * @param bool $allow_phone_number Set to true to allow phone numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPhoneNumber($allow_phone_number)
    {
        $this->container['allow_phone_number'] = $allow_phone_number;

        return $this;
    }

    /**
     * Gets allow_street_address
     *
     * @return bool
     */
    public function getAllowStreetAddress()
    {
        return $this->container['allow_street_address'];
    }

    /**
     * Sets allow_street_address
     *
     * @param bool $allow_street_address Set to true to allow street addresses in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowStreetAddress($allow_street_address)
    {
        $this->container['allow_street_address'] = $allow_street_address;

        return $this;
    }

    /**
     * Gets allow_person_name
     *
     * @return bool
     */
    public function getAllowPersonName()
    {
        return $this->container['allow_person_name'];
    }

    /**
     * Sets allow_person_name
     *
     * @param bool $allow_person_name Set to true to allow person names in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPersonName($allow_person_name)
    {
        $this->container['allow_person_name'] = $allow_person_name;

        return $this;
    }

    /**
     * Gets allow_birth_date
     *
     * @return bool
     */
    public function getAllowBirthDate()
    {
        return $this->container['allow_birth_date'];
    }

    /**
     * Sets allow_birth_date
     *
     * @param bool $allow_birth_date Set to true to allow birth dates in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBirthDate($allow_birth_date)
    {
        $this->container['allow_birth_date'] = $allow_birth_date;

        return $this;
    }

    /**
     * Gets allow_passport_number
     *
     * @return bool
     */
    public function getAllowPassportNumber()
    {
        return $this->container['allow_passport_number'];
    }

    /**
     * Sets allow_passport_number
     *
     * @param bool $allow_passport_number Set to true to allow passport numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPassportNumber($allow_passport_number)
    {
        $this->container['allow_passport_number'] = $allow_passport_number;

        return $this;
    }

    /**
     * Gets allow_drivers_license
     *
     * @return bool
     */
    public function getAllowDriversLicense()
    {
        return $this->container['allow_drivers_license'];
    }

    /**
     * Sets allow_drivers_license
     *
     * @param bool $allow_drivers_license Set to true to allow drivers license numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowDriversLicense($allow_drivers_license)
    {
        $this->container['allow_drivers_license'] = $allow_drivers_license;

        return $this;
    }

    /**
     * Gets allow_social_security_number
     *
     * @return bool
     */
    public function getAllowSocialSecurityNumber()
    {
        return $this->container['allow_social_security_number'];
    }

    /**
     * Sets allow_social_security_number
     *
     * @param bool $allow_social_security_number Set to true to allow social security numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowSocialSecurityNumber($allow_social_security_number)
    {
        $this->container['allow_social_security_number'] = $allow_social_security_number;

        return $this;
    }

    /**
     * Gets allow_taxpayer_id
     *
     * @return bool
     */
    public function getAllowTaxpayerId()
    {
        return $this->container['allow_taxpayer_id'];
    }

    /**
     * Sets allow_taxpayer_id
     *
     * @param bool $allow_taxpayer_id Set to true to allow taxpayer IDs in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowTaxpayerId($allow_taxpayer_id)
    {
        $this->container['allow_taxpayer_id'] = $allow_taxpayer_id;

        return $this;
    }

    /**
     * Gets allow_credit_card_number
     *
     * @return bool
     */
    public function getAllowCreditCardNumber()
    {
        return $this->container['allow_credit_card_number'];
    }

    /**
     * Sets allow_credit_card_number
     *
     * @param bool $allow_credit_card_number Set to true to allow credit card numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardNumber($allow_credit_card_number)
    {
        $this->container['allow_credit_card_number'] = $allow_credit_card_number;

        return $this;
    }

    /**
     * Gets allow_credit_card_expiration_date
     *
     * @return bool
     */
    public function getAllowCreditCardExpirationDate()
    {
        return $this->container['allow_credit_card_expiration_date'];
    }

    /**
     * Sets allow_credit_card_expiration_date
     *
     * @param bool $allow_credit_card_expiration_date Set to true to allow credit card expiration dates in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardExpirationDate($allow_credit_card_expiration_date)
    {
        $this->container['allow_credit_card_expiration_date'] = $allow_credit_card_expiration_date;

        return $this;
    }

    /**
     * Gets allow_credit_card_verification_code
     *
     * @return bool
     */
    public function getAllowCreditCardVerificationCode()
    {
        return $this->container['allow_credit_card_verification_code'];
    }

    /**
     * Sets allow_credit_card_verification_code
     *
     * @param bool $allow_credit_card_verification_code Set to true to allow credit card verification codes in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCreditCardVerificationCode($allow_credit_card_verification_code)
    {
        $this->container['allow_credit_card_verification_code'] = $allow_credit_card_verification_code;

        return $this;
    }

    /**
     * Gets allow_bank_account_number
     *
     * @return bool
     */
    public function getAllowBankAccountNumber()
    {
        return $this->container['allow_bank_account_number'];
    }

    /**
     * Sets allow_bank_account_number
     *
     * @param bool $allow_bank_account_number Set to true to allow bank account numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBankAccountNumber($allow_bank_account_number)
    {
        $this->container['allow_bank_account_number'] = $allow_bank_account_number;

        return $this;
    }

    /**
     * Gets allow_iban
     *
     * @return bool
     */
    public function getAllowIban()
    {
        return $this->container['allow_iban'];
    }

    /**
     * Sets allow_iban
     *
     * @param bool $allow_iban Set to true to allow IBANs in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowIban($allow_iban)
    {
        $this->container['allow_iban'] = $allow_iban;

        return $this;
    }

    /**
     * Gets allow_health_insurance_number
     *
     * @return bool
     */
    public function getAllowHealthInsuranceNumber()
    {
        return $this->container['allow_health_insurance_number'];
    }

    /**
     * Sets allow_health_insurance_number
     *
     * @param bool $allow_health_insurance_number Set to true to allow health insurance numbers in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowHealthInsuranceNumber($allow_health_insurance_number)
    {
        $this->container['allow_health_insurance_number'] = $allow_health_insurance_number;

        return $this;
    }

    /**
     * Gets allow_bearer_token
     *
     * @return bool
     */
    public function getAllowBearerToken()
    {
        return $this->container['allow_bearer_token'];
    }

    /**
     * Sets allow_bearer_token
     *
     * @param bool $allow_bearer_token Set to true to allow bearer tokens in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowBearerToken($allow_bearer_token)
    {
        $this->container['allow_bearer_token'] = $allow_bearer_token;

        return $this;
    }

    /**
     * Gets allow_http_cookie
     *
     * @return bool
     */
    public function getAllowHttpCookie()
    {
        return $this->container['allow_http_cookie'];
    }

    /**
     * Sets allow_http_cookie
     *
     * @param bool $allow_http_cookie Set to true to allow HTTP cookies in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowHttpCookie($allow_http_cookie)
    {
        $this->container['allow_http_cookie'] = $allow_http_cookie;

        return $this;
    }

    /**
     * Gets allow_private_keys
     *
     * @return bool
     */
    public function getAllowPrivateKeys()
    {
        return $this->container['allow_private_keys'];
    }

    /**
     * Sets allow_private_keys
     *
     * @param bool $allow_private_keys Set to true to allow private keys in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowPrivateKeys($allow_private_keys)
    {
        $this->container['allow_private_keys'] = $allow_private_keys;

        return $this;
    }

    /**
     * Gets allow_credentials
     *
     * @return bool
     */
    public function getAllowCredentials()
    {
        return $this->container['allow_credentials'];
    }

    /**
     * Sets allow_credentials
     *
     * @param bool $allow_credentials Set to true to allow credentials (usernames/passwords) in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowCredentials($allow_credentials)
    {
        $this->container['allow_credentials'] = $allow_credentials;

        return $this;
    }

    /**
     * Gets allow_deep_web_urls
     *
     * @return bool
     */
    public function getAllowDeepWebUrls()
    {
        return $this->container['allow_deep_web_urls'];
    }

    /**
     * Sets allow_deep_web_urls
     *
     * @param bool $allow_deep_web_urls Set to true to allow deep web URLs (.onion) in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowDeepWebUrls($allow_deep_web_urls)
    {
        $this->container['allow_deep_web_urls'] = $allow_deep_web_urls;

        return $this;
    }

    /**
     * Gets allow_source_code
     *
     * @return bool
     */
    public function getAllowSourceCode()
    {
        return $this->container['allow_source_code'];
    }

    /**
     * Sets allow_source_code
     *
     * @param bool $allow_source_code Set to true to allow source code in the input text and not flag it as sensitive data.
     *
     * @return $this
     */
    public function setAllowSourceCode($allow_source_code)
    {
        $this->container['allow_source_code'] = $allow_source_code;

        return $this;
    }

    /**
     * Gets allow_ip_address
     *
     * @return bool
     */
    public function getAllowIpAddress()
    {
        return $this->container['allow_ip_address'];
    }

    /**
     * Sets allow_ip_address
     *
     * @param bool $allow_ip_address Set to true to allow IP addresses in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowIpAddress($allow_ip_address)
    {
        $this->container['allow_ip_address'] = $allow_ip_address;

        return $this;
    }

    /**
     * Gets allow_mac_address
     *
     * @return bool
     */
    public function getAllowMacAddress()
    {
        return $this->container['allow_mac_address'];
    }

    /**
     * Sets allow_mac_address
     *
     * @param bool $allow_mac_address Set to true to allow MAC addresses in the input text and not flag them as PII.
     *
     * @return $this
     */
    public function setAllowMacAddress($allow_mac_address)
    {
        $this->container['allow_mac_address'] = $allow_mac_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


