<?php
/**
 * DlpDocumentRedactionResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DlpDocumentRedactionResponse Class Doc Comment
 *
 * @category Class
 * @description Response object for DLP document redaction with 23 PII detection results and redacted document.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DlpDocumentRedactionResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DlpDocumentRedactionResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'redacted_document' => 'string',
        'clean_result' => 'bool',
        'contains_email_address' => 'bool',
        'contains_phone_number' => 'bool',
        'contains_street_address' => 'bool',
        'contains_person_name' => 'bool',
        'contains_birth_date' => 'bool',
        'contains_passport_number' => 'bool',
        'contains_drivers_license' => 'bool',
        'contains_social_security_number' => 'bool',
        'contains_taxpayer_id' => 'bool',
        'contains_credit_card_number' => 'bool',
        'contains_credit_card_expiration_date' => 'bool',
        'contains_credit_card_verification_code' => 'bool',
        'contains_bank_account_number' => 'bool',
        'contains_iban' => 'bool',
        'contains_health_insurance_number' => 'bool',
        'contains_bearer_token' => 'bool',
        'contains_http_cookie' => 'bool',
        'contains_private_keys' => 'bool',
        'contains_credentials' => 'bool',
        'contains_deep_web_urls' => 'bool',
        'contains_source_code' => 'bool',
        'contains_ip_address' => 'bool',
        'contains_mac_address' => 'bool',
        'pages_redacted' => '\Swagger\Client\Model\RedactedPageInfo[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'redacted_document' => 'byte',
        'clean_result' => null,
        'contains_email_address' => null,
        'contains_phone_number' => null,
        'contains_street_address' => null,
        'contains_person_name' => null,
        'contains_birth_date' => null,
        'contains_passport_number' => null,
        'contains_drivers_license' => null,
        'contains_social_security_number' => null,
        'contains_taxpayer_id' => null,
        'contains_credit_card_number' => null,
        'contains_credit_card_expiration_date' => null,
        'contains_credit_card_verification_code' => null,
        'contains_bank_account_number' => null,
        'contains_iban' => null,
        'contains_health_insurance_number' => null,
        'contains_bearer_token' => null,
        'contains_http_cookie' => null,
        'contains_private_keys' => null,
        'contains_credentials' => null,
        'contains_deep_web_urls' => null,
        'contains_source_code' => null,
        'contains_ip_address' => null,
        'contains_mac_address' => null,
        'pages_redacted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'redacted_document' => 'RedactedDocument',
        'clean_result' => 'CleanResult',
        'contains_email_address' => 'ContainsEmailAddress',
        'contains_phone_number' => 'ContainsPhoneNumber',
        'contains_street_address' => 'ContainsStreetAddress',
        'contains_person_name' => 'ContainsPersonName',
        'contains_birth_date' => 'ContainsBirthDate',
        'contains_passport_number' => 'ContainsPassportNumber',
        'contains_drivers_license' => 'ContainsDriversLicense',
        'contains_social_security_number' => 'ContainsSocialSecurityNumber',
        'contains_taxpayer_id' => 'ContainsTaxpayerID',
        'contains_credit_card_number' => 'ContainsCreditCardNumber',
        'contains_credit_card_expiration_date' => 'ContainsCreditCardExpirationDate',
        'contains_credit_card_verification_code' => 'ContainsCreditCardVerificationCode',
        'contains_bank_account_number' => 'ContainsBankAccountNumber',
        'contains_iban' => 'ContainsIBAN',
        'contains_health_insurance_number' => 'ContainsHealthInsuranceNumber',
        'contains_bearer_token' => 'ContainsBearerToken',
        'contains_http_cookie' => 'ContainsHttpCookie',
        'contains_private_keys' => 'ContainsPrivateKeys',
        'contains_credentials' => 'ContainsCredentials',
        'contains_deep_web_urls' => 'ContainsDeepWebUrls',
        'contains_source_code' => 'ContainsSourceCode',
        'contains_ip_address' => 'ContainsIpAddress',
        'contains_mac_address' => 'ContainsMacAddress',
        'pages_redacted' => 'PagesRedacted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'redacted_document' => 'setRedactedDocument',
        'clean_result' => 'setCleanResult',
        'contains_email_address' => 'setContainsEmailAddress',
        'contains_phone_number' => 'setContainsPhoneNumber',
        'contains_street_address' => 'setContainsStreetAddress',
        'contains_person_name' => 'setContainsPersonName',
        'contains_birth_date' => 'setContainsBirthDate',
        'contains_passport_number' => 'setContainsPassportNumber',
        'contains_drivers_license' => 'setContainsDriversLicense',
        'contains_social_security_number' => 'setContainsSocialSecurityNumber',
        'contains_taxpayer_id' => 'setContainsTaxpayerId',
        'contains_credit_card_number' => 'setContainsCreditCardNumber',
        'contains_credit_card_expiration_date' => 'setContainsCreditCardExpirationDate',
        'contains_credit_card_verification_code' => 'setContainsCreditCardVerificationCode',
        'contains_bank_account_number' => 'setContainsBankAccountNumber',
        'contains_iban' => 'setContainsIban',
        'contains_health_insurance_number' => 'setContainsHealthInsuranceNumber',
        'contains_bearer_token' => 'setContainsBearerToken',
        'contains_http_cookie' => 'setContainsHttpCookie',
        'contains_private_keys' => 'setContainsPrivateKeys',
        'contains_credentials' => 'setContainsCredentials',
        'contains_deep_web_urls' => 'setContainsDeepWebUrls',
        'contains_source_code' => 'setContainsSourceCode',
        'contains_ip_address' => 'setContainsIpAddress',
        'contains_mac_address' => 'setContainsMacAddress',
        'pages_redacted' => 'setPagesRedacted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'redacted_document' => 'getRedactedDocument',
        'clean_result' => 'getCleanResult',
        'contains_email_address' => 'getContainsEmailAddress',
        'contains_phone_number' => 'getContainsPhoneNumber',
        'contains_street_address' => 'getContainsStreetAddress',
        'contains_person_name' => 'getContainsPersonName',
        'contains_birth_date' => 'getContainsBirthDate',
        'contains_passport_number' => 'getContainsPassportNumber',
        'contains_drivers_license' => 'getContainsDriversLicense',
        'contains_social_security_number' => 'getContainsSocialSecurityNumber',
        'contains_taxpayer_id' => 'getContainsTaxpayerId',
        'contains_credit_card_number' => 'getContainsCreditCardNumber',
        'contains_credit_card_expiration_date' => 'getContainsCreditCardExpirationDate',
        'contains_credit_card_verification_code' => 'getContainsCreditCardVerificationCode',
        'contains_bank_account_number' => 'getContainsBankAccountNumber',
        'contains_iban' => 'getContainsIban',
        'contains_health_insurance_number' => 'getContainsHealthInsuranceNumber',
        'contains_bearer_token' => 'getContainsBearerToken',
        'contains_http_cookie' => 'getContainsHttpCookie',
        'contains_private_keys' => 'getContainsPrivateKeys',
        'contains_credentials' => 'getContainsCredentials',
        'contains_deep_web_urls' => 'getContainsDeepWebUrls',
        'contains_source_code' => 'getContainsSourceCode',
        'contains_ip_address' => 'getContainsIpAddress',
        'contains_mac_address' => 'getContainsMacAddress',
        'pages_redacted' => 'getPagesRedacted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['redacted_document'] = isset($data['redacted_document']) ? $data['redacted_document'] : null;
        $this->container['clean_result'] = isset($data['clean_result']) ? $data['clean_result'] : null;
        $this->container['contains_email_address'] = isset($data['contains_email_address']) ? $data['contains_email_address'] : null;
        $this->container['contains_phone_number'] = isset($data['contains_phone_number']) ? $data['contains_phone_number'] : null;
        $this->container['contains_street_address'] = isset($data['contains_street_address']) ? $data['contains_street_address'] : null;
        $this->container['contains_person_name'] = isset($data['contains_person_name']) ? $data['contains_person_name'] : null;
        $this->container['contains_birth_date'] = isset($data['contains_birth_date']) ? $data['contains_birth_date'] : null;
        $this->container['contains_passport_number'] = isset($data['contains_passport_number']) ? $data['contains_passport_number'] : null;
        $this->container['contains_drivers_license'] = isset($data['contains_drivers_license']) ? $data['contains_drivers_license'] : null;
        $this->container['contains_social_security_number'] = isset($data['contains_social_security_number']) ? $data['contains_social_security_number'] : null;
        $this->container['contains_taxpayer_id'] = isset($data['contains_taxpayer_id']) ? $data['contains_taxpayer_id'] : null;
        $this->container['contains_credit_card_number'] = isset($data['contains_credit_card_number']) ? $data['contains_credit_card_number'] : null;
        $this->container['contains_credit_card_expiration_date'] = isset($data['contains_credit_card_expiration_date']) ? $data['contains_credit_card_expiration_date'] : null;
        $this->container['contains_credit_card_verification_code'] = isset($data['contains_credit_card_verification_code']) ? $data['contains_credit_card_verification_code'] : null;
        $this->container['contains_bank_account_number'] = isset($data['contains_bank_account_number']) ? $data['contains_bank_account_number'] : null;
        $this->container['contains_iban'] = isset($data['contains_iban']) ? $data['contains_iban'] : null;
        $this->container['contains_health_insurance_number'] = isset($data['contains_health_insurance_number']) ? $data['contains_health_insurance_number'] : null;
        $this->container['contains_bearer_token'] = isset($data['contains_bearer_token']) ? $data['contains_bearer_token'] : null;
        $this->container['contains_http_cookie'] = isset($data['contains_http_cookie']) ? $data['contains_http_cookie'] : null;
        $this->container['contains_private_keys'] = isset($data['contains_private_keys']) ? $data['contains_private_keys'] : null;
        $this->container['contains_credentials'] = isset($data['contains_credentials']) ? $data['contains_credentials'] : null;
        $this->container['contains_deep_web_urls'] = isset($data['contains_deep_web_urls']) ? $data['contains_deep_web_urls'] : null;
        $this->container['contains_source_code'] = isset($data['contains_source_code']) ? $data['contains_source_code'] : null;
        $this->container['contains_ip_address'] = isset($data['contains_ip_address']) ? $data['contains_ip_address'] : null;
        $this->container['contains_mac_address'] = isset($data['contains_mac_address']) ? $data['contains_mac_address'] : null;
        $this->container['pages_redacted'] = isset($data['pages_redacted']) ? $data['pages_redacted'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['redacted_document']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['redacted_document'])) {
            $invalidProperties[] = "invalid value for 'redacted_document', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets redacted_document
     *
     * @return string
     */
    public function getRedactedDocument()
    {
        return $this->container['redacted_document'];
    }

    /**
     * Sets redacted_document
     *
     * @param string $redacted_document The redacted document as a rasterized PDF with PII regions blurred, or the original file if no disallowed PII was found.
     *
     * @return $this
     */
    public function setRedactedDocument($redacted_document)
    {

        if (!is_null($redacted_document) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $redacted_document))) {
            throw new \InvalidArgumentException("invalid value for $redacted_document when calling DlpDocumentRedactionResponse., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['redacted_document'] = $redacted_document;

        return $this;
    }

    /**
     * Gets clean_result
     *
     * @return bool
     */
    public function getCleanResult()
    {
        return $this->container['clean_result'];
    }

    /**
     * Sets clean_result
     *
     * @param bool $clean_result True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.
     *
     * @return $this
     */
    public function setCleanResult($clean_result)
    {
        $this->container['clean_result'] = $clean_result;

        return $this;
    }

    /**
     * Gets contains_email_address
     *
     * @return bool
     */
    public function getContainsEmailAddress()
    {
        return $this->container['contains_email_address'];
    }

    /**
     * Sets contains_email_address
     *
     * @param bool $contains_email_address True if the document contains email addresses.
     *
     * @return $this
     */
    public function setContainsEmailAddress($contains_email_address)
    {
        $this->container['contains_email_address'] = $contains_email_address;

        return $this;
    }

    /**
     * Gets contains_phone_number
     *
     * @return bool
     */
    public function getContainsPhoneNumber()
    {
        return $this->container['contains_phone_number'];
    }

    /**
     * Sets contains_phone_number
     *
     * @param bool $contains_phone_number True if the document contains phone numbers.
     *
     * @return $this
     */
    public function setContainsPhoneNumber($contains_phone_number)
    {
        $this->container['contains_phone_number'] = $contains_phone_number;

        return $this;
    }

    /**
     * Gets contains_street_address
     *
     * @return bool
     */
    public function getContainsStreetAddress()
    {
        return $this->container['contains_street_address'];
    }

    /**
     * Sets contains_street_address
     *
     * @param bool $contains_street_address True if the document contains street addresses.
     *
     * @return $this
     */
    public function setContainsStreetAddress($contains_street_address)
    {
        $this->container['contains_street_address'] = $contains_street_address;

        return $this;
    }

    /**
     * Gets contains_person_name
     *
     * @return bool
     */
    public function getContainsPersonName()
    {
        return $this->container['contains_person_name'];
    }

    /**
     * Sets contains_person_name
     *
     * @param bool $contains_person_name True if the document contains person names.
     *
     * @return $this
     */
    public function setContainsPersonName($contains_person_name)
    {
        $this->container['contains_person_name'] = $contains_person_name;

        return $this;
    }

    /**
     * Gets contains_birth_date
     *
     * @return bool
     */
    public function getContainsBirthDate()
    {
        return $this->container['contains_birth_date'];
    }

    /**
     * Sets contains_birth_date
     *
     * @param bool $contains_birth_date True if the document contains birth dates.
     *
     * @return $this
     */
    public function setContainsBirthDate($contains_birth_date)
    {
        $this->container['contains_birth_date'] = $contains_birth_date;

        return $this;
    }

    /**
     * Gets contains_passport_number
     *
     * @return bool
     */
    public function getContainsPassportNumber()
    {
        return $this->container['contains_passport_number'];
    }

    /**
     * Sets contains_passport_number
     *
     * @param bool $contains_passport_number True if the document contains passport numbers.
     *
     * @return $this
     */
    public function setContainsPassportNumber($contains_passport_number)
    {
        $this->container['contains_passport_number'] = $contains_passport_number;

        return $this;
    }

    /**
     * Gets contains_drivers_license
     *
     * @return bool
     */
    public function getContainsDriversLicense()
    {
        return $this->container['contains_drivers_license'];
    }

    /**
     * Sets contains_drivers_license
     *
     * @param bool $contains_drivers_license True if the document contains drivers license numbers.
     *
     * @return $this
     */
    public function setContainsDriversLicense($contains_drivers_license)
    {
        $this->container['contains_drivers_license'] = $contains_drivers_license;

        return $this;
    }

    /**
     * Gets contains_social_security_number
     *
     * @return bool
     */
    public function getContainsSocialSecurityNumber()
    {
        return $this->container['contains_social_security_number'];
    }

    /**
     * Sets contains_social_security_number
     *
     * @param bool $contains_social_security_number True if the document contains social security numbers.
     *
     * @return $this
     */
    public function setContainsSocialSecurityNumber($contains_social_security_number)
    {
        $this->container['contains_social_security_number'] = $contains_social_security_number;

        return $this;
    }

    /**
     * Gets contains_taxpayer_id
     *
     * @return bool
     */
    public function getContainsTaxpayerId()
    {
        return $this->container['contains_taxpayer_id'];
    }

    /**
     * Sets contains_taxpayer_id
     *
     * @param bool $contains_taxpayer_id True if the document contains taxpayer IDs.
     *
     * @return $this
     */
    public function setContainsTaxpayerId($contains_taxpayer_id)
    {
        $this->container['contains_taxpayer_id'] = $contains_taxpayer_id;

        return $this;
    }

    /**
     * Gets contains_credit_card_number
     *
     * @return bool
     */
    public function getContainsCreditCardNumber()
    {
        return $this->container['contains_credit_card_number'];
    }

    /**
     * Sets contains_credit_card_number
     *
     * @param bool $contains_credit_card_number True if the document contains credit card numbers.
     *
     * @return $this
     */
    public function setContainsCreditCardNumber($contains_credit_card_number)
    {
        $this->container['contains_credit_card_number'] = $contains_credit_card_number;

        return $this;
    }

    /**
     * Gets contains_credit_card_expiration_date
     *
     * @return bool
     */
    public function getContainsCreditCardExpirationDate()
    {
        return $this->container['contains_credit_card_expiration_date'];
    }

    /**
     * Sets contains_credit_card_expiration_date
     *
     * @param bool $contains_credit_card_expiration_date True if the document contains credit card expiration dates.
     *
     * @return $this
     */
    public function setContainsCreditCardExpirationDate($contains_credit_card_expiration_date)
    {
        $this->container['contains_credit_card_expiration_date'] = $contains_credit_card_expiration_date;

        return $this;
    }

    /**
     * Gets contains_credit_card_verification_code
     *
     * @return bool
     */
    public function getContainsCreditCardVerificationCode()
    {
        return $this->container['contains_credit_card_verification_code'];
    }

    /**
     * Sets contains_credit_card_verification_code
     *
     * @param bool $contains_credit_card_verification_code True if the document contains credit card verification codes.
     *
     * @return $this
     */
    public function setContainsCreditCardVerificationCode($contains_credit_card_verification_code)
    {
        $this->container['contains_credit_card_verification_code'] = $contains_credit_card_verification_code;

        return $this;
    }

    /**
     * Gets contains_bank_account_number
     *
     * @return bool
     */
    public function getContainsBankAccountNumber()
    {
        return $this->container['contains_bank_account_number'];
    }

    /**
     * Sets contains_bank_account_number
     *
     * @param bool $contains_bank_account_number True if the document contains bank account numbers.
     *
     * @return $this
     */
    public function setContainsBankAccountNumber($contains_bank_account_number)
    {
        $this->container['contains_bank_account_number'] = $contains_bank_account_number;

        return $this;
    }

    /**
     * Gets contains_iban
     *
     * @return bool
     */
    public function getContainsIban()
    {
        return $this->container['contains_iban'];
    }

    /**
     * Sets contains_iban
     *
     * @param bool $contains_iban True if the document contains IBANs.
     *
     * @return $this
     */
    public function setContainsIban($contains_iban)
    {
        $this->container['contains_iban'] = $contains_iban;

        return $this;
    }

    /**
     * Gets contains_health_insurance_number
     *
     * @return bool
     */
    public function getContainsHealthInsuranceNumber()
    {
        return $this->container['contains_health_insurance_number'];
    }

    /**
     * Sets contains_health_insurance_number
     *
     * @param bool $contains_health_insurance_number True if the document contains health insurance numbers.
     *
     * @return $this
     */
    public function setContainsHealthInsuranceNumber($contains_health_insurance_number)
    {
        $this->container['contains_health_insurance_number'] = $contains_health_insurance_number;

        return $this;
    }

    /**
     * Gets contains_bearer_token
     *
     * @return bool
     */
    public function getContainsBearerToken()
    {
        return $this->container['contains_bearer_token'];
    }

    /**
     * Sets contains_bearer_token
     *
     * @param bool $contains_bearer_token True if the document contains bearer tokens.
     *
     * @return $this
     */
    public function setContainsBearerToken($contains_bearer_token)
    {
        $this->container['contains_bearer_token'] = $contains_bearer_token;

        return $this;
    }

    /**
     * Gets contains_http_cookie
     *
     * @return bool
     */
    public function getContainsHttpCookie()
    {
        return $this->container['contains_http_cookie'];
    }

    /**
     * Sets contains_http_cookie
     *
     * @param bool $contains_http_cookie True if the document contains HTTP cookies.
     *
     * @return $this
     */
    public function setContainsHttpCookie($contains_http_cookie)
    {
        $this->container['contains_http_cookie'] = $contains_http_cookie;

        return $this;
    }

    /**
     * Gets contains_private_keys
     *
     * @return bool
     */
    public function getContainsPrivateKeys()
    {
        return $this->container['contains_private_keys'];
    }

    /**
     * Sets contains_private_keys
     *
     * @param bool $contains_private_keys True if the document contains private keys.
     *
     * @return $this
     */
    public function setContainsPrivateKeys($contains_private_keys)
    {
        $this->container['contains_private_keys'] = $contains_private_keys;

        return $this;
    }

    /**
     * Gets contains_credentials
     *
     * @return bool
     */
    public function getContainsCredentials()
    {
        return $this->container['contains_credentials'];
    }

    /**
     * Sets contains_credentials
     *
     * @param bool $contains_credentials True if the document contains credentials (usernames/passwords).
     *
     * @return $this
     */
    public function setContainsCredentials($contains_credentials)
    {
        $this->container['contains_credentials'] = $contains_credentials;

        return $this;
    }

    /**
     * Gets contains_deep_web_urls
     *
     * @return bool
     */
    public function getContainsDeepWebUrls()
    {
        return $this->container['contains_deep_web_urls'];
    }

    /**
     * Sets contains_deep_web_urls
     *
     * @param bool $contains_deep_web_urls True if the document contains deep web URLs (.onion).
     *
     * @return $this
     */
    public function setContainsDeepWebUrls($contains_deep_web_urls)
    {
        $this->container['contains_deep_web_urls'] = $contains_deep_web_urls;

        return $this;
    }

    /**
     * Gets contains_source_code
     *
     * @return bool
     */
    public function getContainsSourceCode()
    {
        return $this->container['contains_source_code'];
    }

    /**
     * Sets contains_source_code
     *
     * @param bool $contains_source_code True if the document contains source code.
     *
     * @return $this
     */
    public function setContainsSourceCode($contains_source_code)
    {
        $this->container['contains_source_code'] = $contains_source_code;

        return $this;
    }

    /**
     * Gets contains_ip_address
     *
     * @return bool
     */
    public function getContainsIpAddress()
    {
        return $this->container['contains_ip_address'];
    }

    /**
     * Sets contains_ip_address
     *
     * @param bool $contains_ip_address True if the document contains IP addresses.
     *
     * @return $this
     */
    public function setContainsIpAddress($contains_ip_address)
    {
        $this->container['contains_ip_address'] = $contains_ip_address;

        return $this;
    }

    /**
     * Gets contains_mac_address
     *
     * @return bool
     */
    public function getContainsMacAddress()
    {
        return $this->container['contains_mac_address'];
    }

    /**
     * Sets contains_mac_address
     *
     * @param bool $contains_mac_address True if the document contains MAC addresses.
     *
     * @return $this
     */
    public function setContainsMacAddress($contains_mac_address)
    {
        $this->container['contains_mac_address'] = $contains_mac_address;

        return $this;
    }

    /**
     * Gets pages_redacted
     *
     * @return \Swagger\Client\Model\RedactedPageInfo[]
     */
    public function getPagesRedacted()
    {
        return $this->container['pages_redacted'];
    }

    /**
     * Sets pages_redacted
     *
     * @param \Swagger\Client\Model\RedactedPageInfo[] $pages_redacted List of pages that were redacted (had PII regions blurred).
     *
     * @return $this
     */
    public function setPagesRedacted($pages_redacted)
    {
        $this->container['pages_redacted'] = $pages_redacted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


