<?php
/**
 * DlpAdvancedDetectionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DlpAdvancedDetectionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Response object for advanced DLP text detection with 29 PII detection types including health-related data.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DlpAdvancedDetectionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DlpAdvancedDetectionResponse"
     */
    public function testDlpAdvancedDetectionResponse()
    {
    }

    /**
     * Test attribute "clean_result"
     */
    public function testPropertyCleanResult()
    {
    }

    /**
     * Test attribute "contains_email_address"
     */
    public function testPropertyContainsEmailAddress()
    {
    }

    /**
     * Test attribute "contains_phone_number"
     */
    public function testPropertyContainsPhoneNumber()
    {
    }

    /**
     * Test attribute "contains_street_address"
     */
    public function testPropertyContainsStreetAddress()
    {
    }

    /**
     * Test attribute "contains_person_name"
     */
    public function testPropertyContainsPersonName()
    {
    }

    /**
     * Test attribute "contains_birth_date"
     */
    public function testPropertyContainsBirthDate()
    {
    }

    /**
     * Test attribute "contains_passport_number"
     */
    public function testPropertyContainsPassportNumber()
    {
    }

    /**
     * Test attribute "contains_drivers_license"
     */
    public function testPropertyContainsDriversLicense()
    {
    }

    /**
     * Test attribute "contains_social_security_number"
     */
    public function testPropertyContainsSocialSecurityNumber()
    {
    }

    /**
     * Test attribute "contains_taxpayer_id"
     */
    public function testPropertyContainsTaxpayerId()
    {
    }

    /**
     * Test attribute "contains_credit_card_number"
     */
    public function testPropertyContainsCreditCardNumber()
    {
    }

    /**
     * Test attribute "contains_credit_card_expiration_date"
     */
    public function testPropertyContainsCreditCardExpirationDate()
    {
    }

    /**
     * Test attribute "contains_credit_card_verification_code"
     */
    public function testPropertyContainsCreditCardVerificationCode()
    {
    }

    /**
     * Test attribute "contains_bank_account_number"
     */
    public function testPropertyContainsBankAccountNumber()
    {
    }

    /**
     * Test attribute "contains_iban"
     */
    public function testPropertyContainsIban()
    {
    }

    /**
     * Test attribute "contains_health_insurance_number"
     */
    public function testPropertyContainsHealthInsuranceNumber()
    {
    }

    /**
     * Test attribute "contains_bearer_token"
     */
    public function testPropertyContainsBearerToken()
    {
    }

    /**
     * Test attribute "contains_http_cookie"
     */
    public function testPropertyContainsHttpCookie()
    {
    }

    /**
     * Test attribute "contains_private_keys"
     */
    public function testPropertyContainsPrivateKeys()
    {
    }

    /**
     * Test attribute "contains_credentials"
     */
    public function testPropertyContainsCredentials()
    {
    }

    /**
     * Test attribute "contains_deep_web_urls"
     */
    public function testPropertyContainsDeepWebUrls()
    {
    }

    /**
     * Test attribute "contains_source_code"
     */
    public function testPropertyContainsSourceCode()
    {
    }

    /**
     * Test attribute "contains_ip_address"
     */
    public function testPropertyContainsIpAddress()
    {
    }

    /**
     * Test attribute "contains_mac_address"
     */
    public function testPropertyContainsMacAddress()
    {
    }

    /**
     * Test attribute "contains_health_insurance_member_id"
     */
    public function testPropertyContainsHealthInsuranceMemberId()
    {
    }

    /**
     * Test attribute "contains_health_injury_or_disease"
     */
    public function testPropertyContainsHealthInjuryOrDisease()
    {
    }

    /**
     * Test attribute "contains_health_type_of_treatment"
     */
    public function testPropertyContainsHealthTypeOfTreatment()
    {
    }

    /**
     * Test attribute "contains_health_date_and_time_of_treatment"
     */
    public function testPropertyContainsHealthDateAndTimeOfTreatment()
    {
    }

    /**
     * Test attribute "contains_health_plan_beneficiary_number"
     */
    public function testPropertyContainsHealthPlanBeneficiaryNumber()
    {
    }

    /**
     * Test attribute "contains_health_payments_made_for_treatment"
     */
    public function testPropertyContainsHealthPaymentsMadeForTreatment()
    {
    }

    /**
     * Test attribute "contains_faces"
     */
    public function testPropertyContainsFaces()
    {
    }

    /**
     * Test attribute "contains_vehicle_id"
     */
    public function testPropertyContainsVehicleId()
    {
    }

    /**
     * Test attribute "contains_device_id"
     */
    public function testPropertyContainsDeviceId()
    {
    }

    /**
     * Test attribute "contains_names_of_relatives"
     */
    public function testPropertyContainsNamesOfRelatives()
    {
    }

    /**
     * Test attribute "contains_health_universal_record_locator"
     */
    public function testPropertyContainsHealthUniversalRecordLocator()
    {
    }

    /**
     * Test attribute "contains_biometrics"
     */
    public function testPropertyContainsBiometrics()
    {
    }

    /**
     * Test attribute "analysis_rationale"
     */
    public function testPropertyAnalysisRationale()
    {
    }
}
