<?php
/**
 * DlpDocumentRedactionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DlpDocumentRedactionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request object for DLP document redaction with 23 PII detection types.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DlpDocumentRedactionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DlpDocumentRedactionRequest"
     */
    public function testDlpDocumentRedactionRequest()
    {
    }

    /**
     * Test attribute "input_file"
     */
    public function testPropertyInputFile()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "recognition_mode"
     */
    public function testPropertyRecognitionMode()
    {
    }

    /**
     * Test attribute "redaction_mode"
     */
    public function testPropertyRedactionMode()
    {
    }

    /**
     * Test attribute "allow_email_address"
     */
    public function testPropertyAllowEmailAddress()
    {
    }

    /**
     * Test attribute "allow_phone_number"
     */
    public function testPropertyAllowPhoneNumber()
    {
    }

    /**
     * Test attribute "allow_street_address"
     */
    public function testPropertyAllowStreetAddress()
    {
    }

    /**
     * Test attribute "allow_person_name"
     */
    public function testPropertyAllowPersonName()
    {
    }

    /**
     * Test attribute "allow_birth_date"
     */
    public function testPropertyAllowBirthDate()
    {
    }

    /**
     * Test attribute "allow_passport_number"
     */
    public function testPropertyAllowPassportNumber()
    {
    }

    /**
     * Test attribute "allow_drivers_license"
     */
    public function testPropertyAllowDriversLicense()
    {
    }

    /**
     * Test attribute "allow_social_security_number"
     */
    public function testPropertyAllowSocialSecurityNumber()
    {
    }

    /**
     * Test attribute "allow_taxpayer_id"
     */
    public function testPropertyAllowTaxpayerId()
    {
    }

    /**
     * Test attribute "allow_credit_card_number"
     */
    public function testPropertyAllowCreditCardNumber()
    {
    }

    /**
     * Test attribute "allow_credit_card_expiration_date"
     */
    public function testPropertyAllowCreditCardExpirationDate()
    {
    }

    /**
     * Test attribute "allow_credit_card_verification_code"
     */
    public function testPropertyAllowCreditCardVerificationCode()
    {
    }

    /**
     * Test attribute "allow_bank_account_number"
     */
    public function testPropertyAllowBankAccountNumber()
    {
    }

    /**
     * Test attribute "allow_iban"
     */
    public function testPropertyAllowIban()
    {
    }

    /**
     * Test attribute "allow_health_insurance_number"
     */
    public function testPropertyAllowHealthInsuranceNumber()
    {
    }

    /**
     * Test attribute "allow_bearer_token"
     */
    public function testPropertyAllowBearerToken()
    {
    }

    /**
     * Test attribute "allow_http_cookie"
     */
    public function testPropertyAllowHttpCookie()
    {
    }

    /**
     * Test attribute "allow_private_keys"
     */
    public function testPropertyAllowPrivateKeys()
    {
    }

    /**
     * Test attribute "allow_credentials"
     */
    public function testPropertyAllowCredentials()
    {
    }

    /**
     * Test attribute "allow_deep_web_urls"
     */
    public function testPropertyAllowDeepWebUrls()
    {
    }

    /**
     * Test attribute "allow_source_code"
     */
    public function testPropertyAllowSourceCode()
    {
    }

    /**
     * Test attribute "allow_ip_address"
     */
    public function testPropertyAllowIpAddress()
    {
    }

    /**
     * Test attribute "allow_mac_address"
     */
    public function testPropertyAllowMacAddress()
    {
    }
}
