<?php
/**
 * DlpDetectionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DlpDetectionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Response object for DLP text and document detection with 23 PII detection types.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DlpDetectionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DlpDetectionResponse"
     */
    public function testDlpDetectionResponse()
    {
    }

    /**
     * Test attribute "clean_result"
     */
    public function testPropertyCleanResult()
    {
    }

    /**
     * Test attribute "contains_email_address"
     */
    public function testPropertyContainsEmailAddress()
    {
    }

    /**
     * Test attribute "contains_phone_number"
     */
    public function testPropertyContainsPhoneNumber()
    {
    }

    /**
     * Test attribute "contains_street_address"
     */
    public function testPropertyContainsStreetAddress()
    {
    }

    /**
     * Test attribute "contains_person_name"
     */
    public function testPropertyContainsPersonName()
    {
    }

    /**
     * Test attribute "contains_birth_date"
     */
    public function testPropertyContainsBirthDate()
    {
    }

    /**
     * Test attribute "contains_passport_number"
     */
    public function testPropertyContainsPassportNumber()
    {
    }

    /**
     * Test attribute "contains_drivers_license"
     */
    public function testPropertyContainsDriversLicense()
    {
    }

    /**
     * Test attribute "contains_social_security_number"
     */
    public function testPropertyContainsSocialSecurityNumber()
    {
    }

    /**
     * Test attribute "contains_taxpayer_id"
     */
    public function testPropertyContainsTaxpayerId()
    {
    }

    /**
     * Test attribute "contains_credit_card_number"
     */
    public function testPropertyContainsCreditCardNumber()
    {
    }

    /**
     * Test attribute "contains_credit_card_expiration_date"
     */
    public function testPropertyContainsCreditCardExpirationDate()
    {
    }

    /**
     * Test attribute "contains_credit_card_verification_code"
     */
    public function testPropertyContainsCreditCardVerificationCode()
    {
    }

    /**
     * Test attribute "contains_bank_account_number"
     */
    public function testPropertyContainsBankAccountNumber()
    {
    }

    /**
     * Test attribute "contains_iban"
     */
    public function testPropertyContainsIban()
    {
    }

    /**
     * Test attribute "contains_health_insurance_number"
     */
    public function testPropertyContainsHealthInsuranceNumber()
    {
    }

    /**
     * Test attribute "contains_bearer_token"
     */
    public function testPropertyContainsBearerToken()
    {
    }

    /**
     * Test attribute "contains_http_cookie"
     */
    public function testPropertyContainsHttpCookie()
    {
    }

    /**
     * Test attribute "contains_private_keys"
     */
    public function testPropertyContainsPrivateKeys()
    {
    }

    /**
     * Test attribute "contains_credentials"
     */
    public function testPropertyContainsCredentials()
    {
    }

    /**
     * Test attribute "contains_deep_web_urls"
     */
    public function testPropertyContainsDeepWebUrls()
    {
    }

    /**
     * Test attribute "contains_source_code"
     */
    public function testPropertyContainsSourceCode()
    {
    }

    /**
     * Test attribute "contains_ip_address"
     */
    public function testPropertyContainsIpAddress()
    {
    }

    /**
     * Test attribute "contains_mac_address"
     */
    public function testPropertyContainsMacAddress()
    {
    }
}
