<?php
/**
 * DetectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DetectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DetectApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for detectDocument
     *
     * Detect User Data in Document Image.
     *
     */
    public function testDetectDocument()
    {
    }

    /**
     * Test case for detectDocumentAdvanced
     *
     * Detect User Data in Document Image (Advanced).
     *
     */
    public function testDetectDocumentAdvanced()
    {
    }

    /**
     * Test case for detectText
     *
     * Detect User Data in Input Text.
     *
     */
    public function testDetectText()
    {
    }

    /**
     * Test case for detectTextAdvanced
     *
     * Detect User Data in Input Text (Advanced).
     *
     */
    public function testDetectTextAdvanced()
    {
    }
}
