<?php
/**
 * RedactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RedactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RedactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for redactDocument
     *
     * Redact User Data in Document.
     *
     */
    public function testRedactDocument()
    {
    }

    /**
     * Test case for redactDocumentAdvanced
     *
     * Redact User Data in Document (Advanced).
     *
     */
    public function testRedactDocumentAdvanced()
    {
    }

    /**
     * Test case for redactText
     *
     * Redact User Data in Input Text.
     *
     */
    public function testRedactText()
    {
    }

    /**
     * Test case for redactTextAdvanced
     *
     * Redact User Data in Input Text (Advanced).
     *
     */
    public function testRedactTextAdvanced()
    {
    }
}
